### ISSUE TITLE
Shotguns are also now having basic damage for those specific class

### ISSUE THREAD

**Issue by exzoyoloatwrk** [Ch1ckenscoop/svn-rd#2]
Shotguns are also now having 0 damage for those specific class. Whats the base damage of shotgun ?

sm_qcvar asw_skill_accuracy_shotgun_dmg_base          0              //0default = 0, Shotgun Damage.

**Comment by exzoyoloatwrk** [comment]
After searching through the code i found various occurrence of dmg_base 0.
Its working fine but if you edit the damage then it will create the bug of either doing the basic damage while other people are doing updated damage.
I updated the shotgun damage for brutal difficulty and it caused the bug.

**Comment by exzoyoloatwrk** [comment]
dmg_base 0 can be fixed to a ceratin no which will solve the problem.

**Comment by Softcopy** [comment]
> dmg_base 0 can be fixed to a ceratin no which will solve the problem.

all guns dmg_base are default to "0". adjust asw_skill_accuracy_shotgun_dmg_step, it will increases the damage per difficulty level.  asw_skill_accuracy_shotgun_dmg_base can be adjusted as well but not a high value is recommended.
